### ISSUE TITLE
extend API as gettext

### ISSUE THREAD

**Issue by Suhoy95** [c-3po-org/c-3po#63]
Hello, 

Are you planning to extend your API to provide gettext functionality (such as domains and contexts)?

I'm considering this lib to use in work (work with AST, validation and React solution is great). But i have several issues/questions

I hope the cooperation.

**Comment by AlexMost** [comment]
Hello, glad to hear that you have found this library useful for your project. Surely we are planning to add contexts and domains. Going to create a separate issue for this soon, to discuss the format and syntax for those features. If you are interested I will tag you in that issue.

**Comment by Suhoy95** [comment]
great. I like [Jed](http://messageformat.github.io/Jed/) approach: implement old-school gettext API and own modern API. This give our possibility to use *xgettext* utility for extraction (alternative c-3po babel plugin).

**Comment by AlexMost** [comment]
not sure that we will be able to implement old-school gettext API like it was designed for C language, because of the template strings for formatting. Even `ngettext` function behaves a little bit different from as it works in original spec:
```
ngettext(msgid`${ n } banana` `${ n } bananas`, n)
```
1. At least there must be msgid tag before template. For reasons described [here](https://c-3po.js.org/why-use-msgid-for-ngettext.html)
2. As far as I know xgettext is not familiar with es6+ syntax at all. So it just will not be able to extract something like ```gettext(`Hello ${ name }`)```

The goal is to provide concise API for using gettext features. Here is my proposal of how `context` feature can be implemented. 

If you have some ideas in this direction you can join thits conversation - https://github.com/c-3po-org/c-3po/issues/65.
